[colors.primary]
background = "#000000"
foreground = "#b3b3b3"

[colors.normal]
black = "#000000"
blue = "#b3b3ff"
cyan = "#b3eeff"
green = "#b3ffb3"
magenta = "#ffb3ff"
red = "#ff0000"
white = "#ffffff"
yellow = "#eeffb3"

[colors.bright]
black = "#000000"
blue = "#b3b3ff"
cyan = "#b3eeff"
green = "#b3ffb3"
magenta = "#ffb3ff"
red = "#ff0000"
white = "#ffffff"
yellow = "#eeffb3"

[colors.selection]
text = "#b3b3ff"
background = "#666666"

[cursor]
style = { shape = "Underline", blinking = "Always" }
blink_interval = 500

[colors.cursor]
text = "#000000"
cursor = "#b3b3b3"

[font]
normal = { family = "Roboto Mono", style = "Regular" }
bold = { style = "Bold" }
italic = { style = "Italic" }
