[colors.primary]
background = "#000000"
foreground = "#999999"

[colors.normal]
black = "#000000"
blue = "#00ff33"
cyan = "#00ffcc"
green = "#0099ff"
magenta = "#ff00cc"
red = "#ff0033"
white = "#ffffff"
yellow = "#ffff00"

[colors.bright]
black = "#4d4d4d"
blue = "#33adff"
cyan = "#33ffd6"
green = "#33ffff"
magenta = "#ff33d6"
red = "#ff335c"
yellow = "#ffff33"
white = "#b2b2b2"

[colors.selection]
text = "#000000"
background = "#0099ff"

[cursor]
style = { shape = "Underline", blinking = "Always" }
blink_interval = 500

[colors.cursor]
text = "#666666"
cursor = "#0099ff"

[font]
normal = { family = "Roboto Mono", style = "Regular" }
bold = { style = "Bold" }
italic = { style = "Italic" }
