[colors.primary]
background = "#000000"
foreground = "#b3b3b3"

[colors.normal]
black = "#000000"
blue = "#b3b3ff"
cyan = "#b3ffff"
green = "#b3ffb3"
magenta = "#ffb3ff"
red = "#ff0000"
white = "#ffffff"
yellow = "#ffffb3"

[colors.bright]
black = "#4d4d4d"
blue = "#33adff"
cyan = "#33ffd6"
green = "#33ffff"
magenta = "#ff33d6"
red = "#ff335c"
yellow = "#ffff33"
white = "#b2b2b2"

[colors.selection]
text = "#000000"
background = "#b3b3b3"

[cursor]
style = { shape = "Underline", blinking = "Always" }
blink_interval = 500

[colors.cursor]
text = "#000000"
cursor = "#b3b3b3"

[font]
normal = { family = "Roboto Mono", style = "Regular" }
bold = { style = "Bold" }
italic = { style = "Italic" }
