#!/bin/bash

export SALMO_WORKDIR=$(cd $(dirname $0) && pwd)

COMMAND=$1

function help() {
    echo "Usage: salmo {dev|prepare|help}"
    echo ""
    echo "Commands:"
    echo "  dev      Start hot-reload"
    echo "  prepare  Apply config, binary executables, etc."
    echo "  help     Show this help message"
}

case "$COMMAND" in
    dev)
        bash "$SALMO_WORKDIR/commands/dev"
        ;;
    prepare)
        bash "$SALMO_WORKDIR/commands/prepare"
        ;;
    help)
        help
        ;;
    *)
        help
        exit 1
        ;;
esac