#!/bin/bash

. "$SALMO_WORKDIR/lib/errors.sh"
. "$SALMO_WORKDIR/lib/log.sh"

. "$SALMO_WORKDIR/../project.sh"

prepare_home_files() {
    log_info "Preparing home files"

    # Recursively copies everything from the directory path formed by concatenating the value of $SRC_FILES_DIR and $HOME into your home directory ($HOME). All files and subdirectories from the source are duplicated into the destination, preserving the directory structure. If files with the same name exist in the destination, they will be overwritten.
    log_info "Copying all home files from $SRC_FILES_DIR$HOME to $HOME"
    rsync -av "$SRC_FILES_DIR$HOME"/. "$HOME"/

    log_success "Home files copied successfully!"
}

prepare_non_home_files() {
    log_info "Copying all non-home files..."

    # Copy all files except $HOME from $SRC_FILES_DIR to /
    sudo rsync -av --exclude="$HOME" "$SRC_FILES_DIR"/ / 

    log_success "Non-home files copied successfully!"
}

apply_bin() {
    log_info "Applying bin..."

    log_info "Updating permissions for binaries..."
    sudo chmod +x /usr/local/bin/*

    log_info "Reloading bashrc to apply changes..."
    source ~/.bashrc

    log_success "Bin applied successfully!"
}

apply_aliases() {
    log_info "Applying aliases..."

    log_info "Updating permissions for aliases..."
    sudo chmod +x "/usr/local/aliases"/*

    log_info "Ensuring aliases are sourced in ~/.bashrc"
    for alias_file in "/usr/local/aliases"/*.sh; do
        if [[ -f "$alias_file" ]]; then
            alias_source_line="source $alias_file"

            if ! grep -qxF "$alias_source_line" ~/.bashrc; then
                echo "$alias_source_line" >> ~/.bashrc
            fi
        fi
    done

    log_info "Reloading bashrc to apply changes..."
    source ~/.bashrc

    log_success "Aliases applied successfully!"
}

apply_special_files() {
    log_info "Applying special files..."
    
    apply_aliases
    apply_bin

    log_success "Special files applied successfully!"
}

prepare() {
    prepare_home_files
    prepare_non_home_files
    apply_special_files
}

prepare
